"""Refresh a parity fixture from an actual checkout of cryptobot_vCLUADE_v5.

The live repository is read-only to this tool. Expected indicator values and signal
locations are generated by importing the live bot's own `ccbot` package from the checkout.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from parameter_extract.parity import fixture_candles


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ccbot-root", required=True)
    parser.add_argument("--fixture", required=True)
    args = parser.parse_args()

    root = Path(args.ccbot_root).resolve()
    fixture_path = Path(args.fixture)
    sys.path.insert(0, str(root / "src"))

    from ccbot.indicators import calculate_points, entry_conditions  # type: ignore
    from ccbot.models import Team  # type: ignore

    payload = json.loads(fixture_path.read_text(encoding="utf-8"))
    spec = payload["strategy"]
    team = Team(
        id=1,
        symbol=spec["symbol"],
        rsi_period=spec["rsi_period"],
        rsi_entry=spec["rsi_entry"],
        adx_min=spec["adx_min"],
        adx_max=spec["adx_max"],
        exit_mode=spec["exit_mode"],
        rsi_exit=spec.get("rsi_exit"),
        tp_price_pct=spec.get("tp_price_pct"),
        leverage=1,
    ).validated()
    candles = fixture_candles(payload)
    points = calculate_points(
        [candle.high for candle in candles],
        [candle.low for candle in candles],
        [candle.close for candle in candles],
        team.rsi_period,
    )

    selected = [int(row["index"]) for row in payload["expected"]["points"]]
    payload["expected"]["points"] = [
        {"index": index, **points[index].as_dict()}
        for index in selected
        if points[index] is not None
    ]
    signals = []
    for index in range(1, len(candles)):
        previous, current = points[index - 1], points[index]
        if previous is None or current is None:
            continue
        if all(entry_conditions(previous, current, team).values()):
            signals.append(
                {"candle_index": index, "timestamp_ms": candles[index].close_time_ms}
            )
    payload["expected"]["signals"] = signals

    commit = subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
    ).strip()
    payload["source"] = {
        "repository": "aricansoft2022/cryptobot_vCLUADE_v5",
        "commit": commit,
        "file": "src/ccbot/indicators.py",
        "note": "Expected values generated by tools/refresh_parity_fixture.py from this checkout.",
    }
    fixture_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"updated {fixture_path} from live bot commit {commit}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
